//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class roomCheckInInfoView
    {
        public int checkInID { get; set; }
        [DisplayName("入住房间")]

        public int checkInRoomID { get; set; }
        [DisplayName("入住客人")]

        public int checkInGuestID { get; set; }
        [DisplayName("入住状态")]

        public int checkInStatus { get; set; }
        [DisplayName("备注")]

        public string checkInRemark { get; set; }
        [DisplayName("入住时间")]

        public System.DateTime checkInTime { get; set; }
        public int checkInCreatorID { get; set; }
        [DisplayName("退房时间")]

        public System.DateTime checkOutTime { get; set; }
        [DisplayName("已交押金")]

        public decimal checkInDeposit { get; set; }


    }
}
