//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class roomRoomInfoView
    {
    
    
        public int roomID { get; set; }
        [DisplayName("房间名称")]

        public string roomName { get; set; }
        [DisplayName("房间类型")]

        public int roomTypeID { get; set; }
        [DisplayName("房间状态")]

        public int roomStatus { get; set; }
        public int roomCreatorID { get; set; }
        public System.DateTime roomCreateTime { get; set; }
    
    
    
    
    }
}
