//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class roomTypeView
    {
    
    
        public int typeID { get; set; }
        [DisplayName("房间类型名称")]

        public string typeName { get; set; }
        [DisplayName("床位数")]
        
        public int bedNum { get; set; }
        [DisplayName("价格")]

        public decimal price { get; set; }
    
    
    }
}
