//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class roomGuestInfoView
    {


    
        public int guestID { get; set; }
        [DisplayName("客户姓名")]    
        public string guestName { get; set; }
        [DisplayName("客户电话")]

        public string guestPhone { get; set; }
        [DisplayName("客户类型")]

        public int guestStatus { get; set; }
        public int guestCreatorID { get; set; }
        public System.DateTime guestCreateTime { get; set; }
    
    
    
    }
}
