//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class sysKeyValueView
    {


        public int KID { get; set; }
        [DisplayName("数据字典父级编号")]
        public int ParentID { get; set; }
        [DisplayName("数据字典类型")]

        public int KType { get; set; }
        [DisplayName("数据字典名称")]

        public string KName { get; set; }
        [DisplayName("数据字典值")]

        public string Kvalue { get; set; }
        [DisplayName("数据字典备注")]

        public string KRemark { get; set; }








    }
}
