//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class sysMenusView
    {

        [DisplayName("菜单ID")]
        public int mID { get; set; }
        [DisplayName("父级菜单ID")]

        public int mParentID { get; set; }
        [DisplayName("菜单名")]

        public string mName { get; set; }
        [DisplayName("地址")]

        public string mUrl { get; set; }
        [DisplayName("区域名")]

        public string mArea { get; set; }
        [DisplayName("控制器")]

        public string mController { get; set; }
        [DisplayName("方法名")]

        public string mAction { get; set; }
        [DisplayName("排序号")]
        public int mSortid { get; set; }
        [DisplayName("状态")]
        public int mStatus { get; set; }
        [DisplayName("图标")]
        public string mPicname { get; set; }
        [DisplayName("菜单级别")]
        public int mLevel { get; set; }
        public string mExp1 { get; set; }
        public Nullable<int> mExp2 { get; set; }
        public int mCreatorID { get; set; }
        public System.DateTime mCreateTime { get; set; }
        public Nullable<int> mUpdateID { get; set; }
        public System.DateTime mUpdateTime { get; set; }



    }
}
