//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class sysUserInfoView
    {
        //[DisplayName("验证码"), Required(ErrorMessage = "验证码非空")]
        //public string Vcode { get; set; }
        public int uID { get; set; }
        [DisplayName("用户名"), Required(ErrorMessage = "用户名非空")]
        public string uLoginName { get; set; }
        [DisplayName("密码"), Required(ErrorMessage = "密码非空")]
        public string uLoginPWD { get; set; }
        [DisplayName("真实姓名")]

        public string uRealName { get; set; }
        [DisplayName("电话号码")]

        public string uTelphone { get; set; }
        [DisplayName("手机号码")]

        public string uMobile { get; set; }
        [DisplayName("电子邮箱")]

        public string uEmial { get; set; }
        [DisplayName("QQ号")]

        public string uQQ { get; set; }
        [DisplayName("性别")]

        public int uGender { get; set; }
        [DisplayName("状态")]

        public int uStatus { get; set; }
        [DisplayName("连锁公司")]

        public int uCompanyID { get; set; }
        [DisplayName("部门")]

        public Nullable<int> uDepID { get; set; }
        [DisplayName("工作组")]

        public Nullable<int> uWorkGroupID { get; set; }
        public string uRemark { get; set; }
        public int uCreatorID { get; set; }
        public System.DateTime uCreateTime { get; set; }
        public Nullable<int> uUpdateID { get; set; }
        public System.DateTime uUpdateTime { get; set; }






    }
}
