//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class wfWorkNodesView
    {

        
        public int wfnID { get; set; }
        public int wfID { get; set; }
        public int wfnOrderNo { get; set; }
        [DisplayName("节点类型")]
        public int wfNodeType { get; set; }
        [DisplayName("节点标题")]
        public string wfNodeTitle { get; set; }
        [DisplayName("处理逻辑")]

        public string wfnBizMethod { get; set; }
        [DisplayName("审批时限")]

        public decimal wfnMaxNum { get; set; }
        [DisplayName("审批角色类型")]

        public int wfnRoleType { get; set; }
        public Nullable<int> wfnExt1 { get; set; }
        public string wfnExt2 { get; set; }
        public int fCreatorID { get; set; }
        public System.DateTime fCreateTime { get; set; }
        public Nullable<int> fUpdateID { get; set; }
        public Nullable<System.DateTime> fUpdateTime { get; set; }







    }
}
