//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomRoomInfo
    {
        public roomRoomInfo() 
        {
            this.roomCheckInInfo = new HashSet<roomCheckInInfo>();
        }
    
        public int roomID { get; set; }
        public string roomName { get; set; }
        public int roomTypeID { get; set; }
        public int roomStatus { get; set; }
        public int roomCreatorID { get; set; }
        public System.DateTime roomCreateTime { get; set; }
    
        public virtual ICollection<roomCheckInInfo> roomCheckInInfo { get; set; }
        public virtual roomKeyValue roomKeyValue { get; set; }
        public virtual roomType roomType { get; set; }
    }
}
