//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomKeyValue
    {
        public roomKeyValue() 
        {
            this.roomCheckInInfo = new HashSet<roomCheckInInfo>();
            this.roomGuestInfo = new HashSet<roomGuestInfo>();
            this.roomRoomInfo = new HashSet<roomRoomInfo>();
        }
    
        public string Kvalue { get; set; }
        public int KID { get; set; }
        public string KName { get; set; }
        public int KType { get; set; }
    
        public virtual ICollection<roomCheckInInfo> roomCheckInInfo { get; set; }
        public virtual ICollection<roomGuestInfo> roomGuestInfo { get; set; }
        public virtual ICollection<roomRoomInfo> roomRoomInfo { get; set; }
    }
}
