//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomGuestInfo
    {
        public roomGuestInfo() 
        {
            this.roomCheckInInfo = new HashSet<roomCheckInInfo>();
        }
    
        public int guestID { get; set; }
        public string guestName { get; set; }
        public string guestPhone { get; set; }
        public int guestStatus { get; set; }
        public int guestCreatorID { get; set; }
        public System.DateTime guestCreateTime { get; set; }
    
        public virtual ICollection<roomCheckInInfo> roomCheckInInfo { get; set; }
        public virtual roomKeyValue roomKeyValue { get; set; }
    }
}
