//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm19.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomCheckInInfo
    {
        public int checkInID { get; set; }
        public int checkInRoomID { get; set; }
        public int checkInGuestID { get; set; }
        public int checkInStatus { get; set; }
        public string checkInRemark { get; set; }
        public System.DateTime checkInTime { get; set; }
        public int checkInCreatorID { get; set; }
        public System.DateTime checkOutTime { get; set; }
        public decimal checkInDeposit { get; set; }
    
        public virtual roomGuestInfo roomGuestInfo { get; set; }
        public virtual roomKeyValue roomKeyValue { get; set; }
        public virtual roomRoomInfo roomRoomInfo { get; set; }
    }
}
